services:
  db:
    image: mysql:8.0
    container_name: tipbot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tipbot_db
      MYSQL_USER: tipbot
      MYSQL_PASSWORD: supersecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  bot:
    build: .
    container_name: tipbot_bot
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/tip-swap
    command: python index.py

volumes:
  db_data:
